### ISSUE TITLE
Fix postgresql init scripts line ending to work with Windows

### ISSUE THREAD

**Issue by brocaar** [brocaar/loraserver-docker#10]
> The problem is Windows versus Unix line termination in the three shell scripts in the folder \configuration\postgresql\initdb

> These files were written into my working directory (git clone) with CR LF line termination. Changing these three files to LF line termination, it appears all the LoRaServer services startup properly when “docker-compose up” is issued. Startup logs look clean and I am able to access http://localhost:8080

> I believe the folders containing the above files need a .gitattributes file which forces preservation of the LF line termination when these files are written to the working directory as a result of a git clone.

https://forum.loraserver.io/t/loraserver-docker-compose-wont-run-on-win-10/3592/3

**Comment by tinkotvas** [comment]
I believe this is a cross-platform issue, which could be resolved using a **.gitattributes** with:
`*.sh		text eol=lf`

**Comment by brocaar** [comment]
@tinkotvas great! would you be able to create a pull-request? Do you think this must also be applied to the `*.toml` files? Although it seems to work, I believe these are also converted to Windows line-endings, before mounted to a Linux based container.

If you would be able to validate this + create a pull-request, that would be appreciated :-)

**Comment by tinkotvas** [comment]
*.toml do save as CRLF on Windows for me, but since they weren't giving me any issues I haven't touched them.
