### ISSUE TITLE
lora-app-server not using environmental variables

### ISSUE THREAD

**Issue by tinkotvas** [brocaar/loraserver-docker#13]
Hello,

I'm trying to use environmental variables (from what I understand in commit [0485199 ](https://github.com/brocaar/lora-app-server/commit/04851996ab8e682738a046cd52702acaa03bd6c3) in **lora-app-server**, there should be support for this) instead of the configuration file **lora-app-server.toml**, but it's failing on finding the values/vars.

I've have first verified and set the values in the **lora-app-server.toml** to be sure that it's working with the generated token on http://localhost:8080/api which worked fine.

**Error**
time="2019-02-28T12:11:31Z" level=fatal msg="jwt secret must be set for external api"

In the **docker-compose.yml** I've modified like below:
```
  appserver:
    image: loraserver/lora-app-server:2
    ports:
      - 8080:8080
    environment:
      - APPLICATION_SERVER.EXTERNAL_API.JWT_SECRET=19ELC2DYRUK66YWAML0SPU13SRDTFB5V
```

I can find the environmental variable on in the docker container, but the **lora-app-server** doesn't seem to be able to identify it, it's **only working when set in** the **lora-app-server.toml**

The reason why I'm doing this is that I want to center my config to the **docker-compose.yml** file instead of having to edit in several locations. I'm also using the token generated of the jwt secret for my app and this is working > (to verify env passing in docker-compose working) and for my case it's grabbable via **process.env.API_TOKEN** (nodejs)
```
    environment:
      - API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsb3JhLWFwcC1zZXJ2ZXIiLCJhdWQiOiJsb3JhLWFwcC1zZXJ2ZXIiLCJuYmYiOjE1MDg3NDgxNTAsImV4cCI6MTYwMDAwMDAwMCwic3ViIjoiYWRtaW4iLCJ1c2VybmFtZSI6ImFkbWluIn0.P0lE0Q1TstDLnMcSpA94q-NtQUgBzahkc3vLFkHpT8k
```

I've been trough the documentation yesterday, and almost all day today but am unable to find anything to help me move forward with using environmental variables in this setup.

Kind regards,
Tin

**Comment by brocaar** [comment]
As you're using `loraserver/lora-app-server:2` there is no guarantee that you have the version which supports environment variables when an older version is in your cache. Please try again using `loraserver/lora-app-server:2.5.1`. You might also need to `docker-compose stop && docker-compose rm` to make sure a new container is created using the correct image version.

**Comment by tinkotvas** [comment]
Makes perfect sense, yes it does.

I was checking on https://hub.docker.com/r/loraserver/lora-app-server/tags and saw the update for v.2 was 14 days ago, and the commit over a month old, and drew a silly conclusion.

It's working perfectly with 2.5.1, sorry for the bother!
