### ISSUE TITLE
Packet forwarder installation?

### ISSUE THREAD

**Issue by krasi-georgiev** [brocaar/loraserver-docker#16]
IIUC this docker install doesn't include the packet forwarder?

Is there a plan to add it or at least add description how to install separately?

**Comment by blocknonip** [comment]
The packet forwarder normally resides on a device with a [LoRa radio](https://www.thethingsnetwork.org/docs/gateways/packet-forwarder/) (i.e. a gateway). I'm not sure how much value there would be having it in a container without a radio. What are you looking to accomplish?

**Comment by brocaar** [comment]
There are no plans to include this. Different gateways are using different HAL libraries and / or variables. Usually the information (and packages) to get started with the Semtech UDP packet-forwarder comes from the gateway vendor. Some vendors have their own packet-forwarder, which is compatible with the Semtech UDP protocol.

**Comment by krasi-georgiev** [comment]
Yes of course it will be installed where the gateway is, but simple use cases would have all components on the same host - forwarder, server etc. Similar to the lora-gateway-os.

Even if having it in a container doesn't work, at least some docs and links on where and how to install a packet forwarder would be really helpful.

**Comment by krasi-georgiev** [comment]
I guess what I am after is either a docker image for the forwarder container or some instructions on how to install it.

https://github.com/Lora-net/packet_forwarder

**Comment by krasi-georgiev** [comment]
would you point me to some docs on how to install the Semtek port forwarder and some example settings for the lora server and I will try to build a docker image for it.

**Comment by ltfschoen** [comment]
@krasi-georgiev 
* https://www.loraserver.io/lora-gateway-bridge/overview/
* https://github.com/Lora-net/packet_forwarder
* https://github.com/Lora-net/packet_forwarder/tree/master/lora_pkt_fwd
* https://github.com/lorabasics/basicstation
* https://doc.sm.tc/station/
* https://www.loraserver.io/guides/troubleshooting/gateway/
* https://www.loraserver.io/loraserver/install/config/

**Comment by ltfschoen** [comment]
* https://www.loraserver.io/lora-gateway-bridge/install/config/ 

> LoRa Gateway Bridge abstracts the packet_forwarder protocol into JSON over MQTT

* documentation & support: https://docs.loraserver.io/lora-gateway-bridge
* source & copyright information: https://github.com/brocaar/lora-gateway-bridge

**Comment by krasi-georgiev** [comment]
Thanks, wow, that quite a lot of info :+1: 

Will need to spend some time to see how it all fits together and find the correlation and what would I need for the docker setup.

**Comment by krasi-georgiev** [comment]
btw if you have the time It would help to add some more details for these links and which of these are currently missing from the current docker installation guide so I know what I would need to try and add.

**Comment by krasi-georgiev** [comment]
just to clarify I am after the same setup as the [LoRa Gateway OS](https://www.loraserver.io/lora-gateway-os/overview/) (I will be using Rpi 3 with [RAK833](https://uk.pi-supply.com/products/iot-lora-gateway-hat-for-raspberry-pi)). 

I would appreciate some more details on what would need to add to the existing docker install to have a setup like the LoRa Gateway OS.

**Comment by krasi-georgiev** [comment]
From what I see in the [docker-compose file](https://github.com/brocaar/loraserver-docker/blob/master/docker-compose.yml#L17)  the gateway bridge already has a docker image so all I need to figure out is to make the Semtec packet forwarded compiled and docker-ized.

I imagine you already have some process for building this as part of the Gateway OS so maybe I can reuse big part of it.

**Comment by krasi-georgiev** [comment]
I figured it out by looking at this guide
https://github.com/Lora-net/packet_forwarder/wiki/Use-with-Raspberry-Pi

**Comment by krasi-georgiev** [comment]
and here is the docker image with config file for the rak833 Rpi hat module.

https://github.com/arribada/loraserver-docker

Other modules can be suported just by passing the correct config file as a container mount.
