### ISSUE TITLE
Can't see network server after start

### ISSUE THREAD

**Issue by boskiv** [brocaar/loraserver-docker#20]
I have start a stack with `docker-compose up -d`
Login to app server
Create a new network server `loraserver:8000`
When I creating a gateway, i cant choose my created network server from list, because it's empty.
What I need to check ?
<img width="1792" alt="Screenshot 2019-08-17 at 4 56 28 PM" src="https://user-images.githubusercontent.com/1939783/63212651-86fee500-c110-11e9-926d-408a962b0ee6.png">
<img width="1792" alt="Screenshot 2019-08-17 at 4 56 44 PM" src="https://user-images.githubusercontent.com/1939783/63212652-89613f00-c110-11e9-8872-347630de17aa.png">
<img width="1392" alt="Screenshot 2019-08-17 at 4 56 52 PM" src="https://user-images.githubusercontent.com/1939783/63212654-8a926c00-c110-11e9-9e0c-f01993ec83c6.png">

**Comment by brocaar** [comment]
Please see the help-text below the dropdown :wink: 

> Select the network-server to which the gateway will connect. **When no network-servers are available in the dropdown, make sure a service-profile exists for this organization.**
