### ISSUE TITLE
The env variable identifiers shouldn't include dots.

### ISSUE THREAD

**Issue by krasi-georgiev** [brocaar/loraserver-docker#22]
https://github.com/brocaar/loraserver-docker/blob/master/docker-compose-env.yml

For example: `INTEGRATION.MQTT.AUTH.GENERIC.SERVER`. This is not a valid env variable idtentifier and fails when trying use with a compose file.
It also fails with simple bash command like: 
```
export INTEGRATION.MQTT.AUTH.GENERIC.SERVER=tcp://mosquitto:1883
bash: export: `INTEGRATION.MQTT.AUTH.GENERIC.SERVER=tcp://mosquitto:1883': not a valid identifier
```

**Comment by blocknonip** [comment]
You probably want to file a bug against the affected server component. I've had no issues with dotted variables in either docker-compose (including `docker-compose-env.yml`) or Kubernetes, but as you've noted, shells don't like it.

**Comment by krasi-georgiev** [comment]
yes you are right I tried a different docker-compose cli version and it worked.

btw most repos still reference different env variable names. 
for example
https://github.com/brocaar/lora-gateway-bridge/blob/8f8bf2c65eb1cce18962026c60e515c5b06c7f74/docker-compose.yml#L14
