### ISSUE TITLE
The device OTAA not activated.

### ISSUE THREAD

**Issue by garvi-x** [brocaar/loraserver-docker#8]
Hello!

I tried to connect a device on my loraserver (after creating a network server, service profile, device profile, gateway, etc...) and I can't get the created device to activate.

The only component I couldn't build was geolocation. The certificates are placed, and it doesn't seem that in the log there is any error related to this.

LoraServer log:
<pre>time=&quot;2018-10-16T07:22:18Z&quot; level=info msg=&quot;starting LoRa Server&quot; band=EU_863_870 docs=&quot;https://docs.loraserver.io/&quot; net_id=123456 version=2.3.0
time=&quot;2018-10-16T07:22:18Z&quot; level=info msg=&quot;setup redis connection pool&quot; url=&quot;redis://redis:6379&quot;
time=&quot;2018-10-16T07:22:18Z&quot; level=info msg=&quot;connecting to postgresql&quot;
time=&quot;2018-10-16T07:22:19Z&quot; level=error msg=&quot;ping database error, will retry in 2s: pq: the database system is starting up&quot;
time=&quot;2018-10-16T07:22:21Z&quot; level=info msg=&quot;gateway/mqtt: connecting to mqtt broker&quot; server=&quot;tcp://mosquitto:1883&quot;
time=&quot;2018-10-16T07:22:21Z&quot; level=error msg=&quot;gateway/mqtt: connecting to mqtt broker failed, will retry in 2s: Network Error : dial tcp 172.19.0.4:1883: connect: connection refused&quot;
time=&quot;2018-10-16T07:22:23Z&quot; level=info msg=&quot;no geolocation-server configured&quot;
time=&quot;2018-10-16T07:22:23Z&quot; level=info msg=&quot;backend/gateway: connected to mqtt server&quot;
time=&quot;2018-10-16T07:22:23Z&quot; level=info msg=&quot;gateway/mqtt: subscribing to rx topic&quot; qos=0 topic=gateway/+/rx
time=&quot;2018-10-16T07:22:23Z&quot; level=info msg=&quot;configuring join-server client&quot; ca_cert= server=&quot;http://appserver:8003&quot; tls_cert= tls_key=
time=&quot;2018-10-16T07:22:23Z&quot; level=info msg=&quot;no network-controller configured&quot;
time=&quot;2018-10-16T07:22:23Z&quot; level=info msg=&quot;applying database migrations&quot;
time=&quot;2018-10-16T07:22:23Z&quot; level=info msg=&quot;gateway/mqtt: subscribing to stats topic&quot; qos=0 topic=gateway/+/stats
time=&quot;2018-10-16T07:22:23Z&quot; level=info msg=&quot;backend/gateway: subscribing to ack topic&quot; qos=0 topic=gateway/+/ack
time=&quot;2018-10-16T07:22:23Z&quot; level=info msg=&quot;migrations applied&quot; count=0
time=&quot;2018-10-16T07:22:23Z&quot; level=info msg=&quot;starting api server&quot; bind=&quot;0.0.0.0:8000&quot; ca-cert=/certs/ca/ca.pem tls-cert=/certs/loraserver/api/server/loraserver-api-server.pem tls-key=/certs/loraserver/api/server/loraserver-api-server-key.pem
time=&quot;2018-10-16T07:22:23Z&quot; level=info msg=&quot;starting downlink device-queue scheduler&quot;
time=&quot;2018-10-16T07:22:23Z&quot; level=info msg=&quot;starting multicast scheduler&quot;
time=&quot;2018-10-16T07:22:48Z&quot; level=info msg=&quot;gateway/mqtt: gateway stats packet received&quot; gateway_id=88c255fffe6c8bf3
time=&quot;2018-10-16T07:22:48Z&quot; level=info msg=&quot;gateway updated&quot; gateway_id=88c255fffe6c8bf3
time=&quot;2018-10-16T07:23:18Z&quot; level=info msg=&quot;gateway/mqtt: gateway stats packet received&quot; gateway_id=88c255fffe6c8bf3
time=&quot;2018-10-16T07:23:18Z&quot; level=info msg=&quot;gateway updated&quot; gateway_id=88c255fffe6c8bf3
time=&quot;2018-10-16T07:23:48Z&quot; level=info msg=&quot;gateway/mqtt: gateway stats packet received&quot; gateway_id=88c255fffe6c8bf3
time=&quot;2018-10-16T07:23:48Z&quot; level=info msg=&quot;gateway updated&quot; gateway_id=88c255fffe6c8bf3
time=&quot;2018-10-16T07:23:59Z&quot; level=info msg=&quot;gateway/mqtt: uplink frame received&quot;
time=&quot;2018-10-16T07:23:59Z&quot; level=error msg=&quot;processing uplink frame error&quot; data_base64=&quot;QPQqASaAEQABNPZdGTumEx9aV8g=&quot; error=&quot;get device-session error: device-session does not exist or invalid fcnt or mic&quot;
time=&quot;2018-10-16T07:24:18Z&quot; level=info msg=&quot;gateway/mqtt: gateway stats packet received&quot; gateway_id=88c255fffe6c8bf3
time=&quot;2018-10-16T07:24:18Z&quot; level=info msg=&quot;gateway updated&quot; gateway_id=88c255fffe6c8bf3
time=&quot;2018-10-16T07:24:48Z&quot; level=info msg=&quot;gateway/mqtt: gateway stats packet received&quot; gateway_id=88c255fffe6c8bf3
time=&quot;2018-10-16T07:24:48Z&quot; level=info msg=&quot;gateway updated&quot; gateway_id=88c255fffe6c8bf3</pre>

LoraAppServer log:
<pre>time=&quot;2018-10-16T07:22:20Z&quot; level=info msg=&quot;starting LoRa App Server&quot; docs=&quot;https://www.loraserver.io/&quot; version=2.3.0
time=&quot;2018-10-16T07:22:20Z&quot; level=info msg=&quot;connecting to postgresql&quot;
time=&quot;2018-10-16T07:22:20Z&quot; level=info msg=&quot;setup redis connection pool&quot;
time=&quot;2018-10-16T07:22:20Z&quot; level=info msg=&quot;handler/mqtt: TLS config is empty&quot;
time=&quot;2018-10-16T07:22:20Z&quot; level=info msg=&quot;handler/mqtt: connecting to mqtt broker&quot; server=&quot;tcp://mosquitto:1883&quot;
time=&quot;2018-10-16T07:22:21Z&quot; level=info msg=&quot;applying database migrations&quot;
time=&quot;2018-10-16T07:22:21Z&quot; level=info msg=&quot;handler/mqtt: connected to mqtt broker&quot;
time=&quot;2018-10-16T07:22:21Z&quot; level=info msg=&quot;handler/mqtt: subscribing to tx topic&quot; qos=0 topic=application/+/device/+/tx
time=&quot;2018-10-16T07:22:21Z&quot; level=info msg=&quot;migrations applied&quot; count=0
time=&quot;2018-10-16T07:22:21Z&quot; level=info msg=&quot;starting application-server api&quot; bind=&quot;0.0.0.0:8001&quot; ca-cert=/certs/ca/ca.pem tls-cert=/certs/lora-app-server/api/server/lora-app-server-api-server.pem tls-key=/certs/lora-app-server/api/server/lora-app-server-api-server-key.pem
time=&quot;2018-10-16T07:22:21Z&quot; level=info msg=&quot;starting join-server api&quot; bind=&quot;0.0.0.0:8003&quot; ca_cert= tls_cert= tls_key=
time=&quot;2018-10-16T07:22:21Z&quot; level=info msg=&quot;starting client api server&quot; bind=&quot;0.0.0.0:8080&quot; tls-cert=/etc/lora-app-server/certs/http.pem tls-key=/etc/lora-app-server/certs/http-key.pem
time=&quot;2018-10-16T07:22:21Z&quot; level=info msg=&quot;registering rest api handler and documentation endpoint&quot; path=/api
</pre>

LoraGatewayBridge log:
<pre>time=&quot;2018-10-16T07:22:20Z&quot; level=info msg=&quot;starting LoRa Gateway Bridge&quot; docs=&quot;https://www.loraserver.io/lora-gateway-bridge/&quot; version=2.6.0
time=&quot;2018-10-16T07:22:20Z&quot; level=info msg=&quot;backend: set max reconnect interval: 10m0s&quot;
time=&quot;2018-10-16T07:22:20Z&quot; level=info msg=&quot;backend: TLS config is empty&quot;
time=&quot;2018-10-16T07:22:20Z&quot; level=info msg=&quot;backend: connecting to mqtt broker&quot; server=&quot;tcp://mosquitto:1883&quot;
time=&quot;2018-10-16T07:22:21Z&quot; level=info msg=&quot;gateway: starting gateway udp listener&quot; addr=&quot;0.0.0.0:1700&quot;
time=&quot;2018-10-16T07:22:21Z&quot; level=info msg=&quot;backend: connected to mqtt broker&quot;
time=&quot;2018-10-16T07:22:21Z&quot; level=info msg=&quot;backend: subscribing to topic&quot; qos=0 topic=gateway/88c255fffe6c8bf3/tx
time=&quot;2018-10-16T07:22:21Z&quot; level=info msg=&quot;backend: subscribing to topic&quot; qos=0 topic=gateway/88c255fffe6c8bf3/config
time=&quot;2018-10-16T07:22:48Z&quot; level=info msg=&quot;gateway: stat packet received&quot; addr=&quot;172.19.0.1:48442&quot; mac=88c255fffe6c8bf3
time=&quot;2018-10-16T07:22:48Z&quot; level=info msg=&quot;backend: publishing packet&quot; qos=0 topic=gateway/88c255fffe6c8bf3/stats
</pre>

**Comment by garvi-x** [comment]
I'm continue with the same problem.

**Comment by brocaar** [comment]
Please use the forum for support related questions: https://forum.loraserver.io/ :)
