### ISSUE TITLE
Mosquitto with auth Plugin 

### ISSUE THREAD

**Issue by jofleck** [brocaar/loraserver-docker#9]
Feature request:. It would be really nice if a preconfigured Mosquitto with auth plugin would be included :)

**Comment by brocaar** [comment]
The loraserver-docker repo serves as an example to quickly bootstrap LoRa Server + dependencies with the min. set of configuration. I'm not planning to extend this with MQTT authentication / authorization as there are various ways of doing so and different use-cases might need different ways of setting this up.

You will find various options to configure MQTT authentication / authorization here:
https://www.loraserver.io/guides/mqtt-authentication/
